buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://maven.fabricmc.net/" }
    }
    dependencies {
        classpath 'net.fabricmc:fabric-loom:1.7-SNAPSHOT'
    }
}

apply plugin: 'net.fabricmc.fabric-loom'
apply plugin: 'maven-publish'

version = project.mod_version
group = project.maven_group

loom {
    // 26.x ve sonrası için boş bırakıyoruz
}

repositories {
    mavenCentral()
    maven { url "https://maven.fabricmc.net/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    
    // 26.x için "modImplementation" yerine "implementation"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    def version = project.version
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }
}
