plugins {
    id 'net.fabricmc.loom' version '1.10.5'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
    maven { url "https://maven.fabricmc.net/" }
    maven { url "https://libraries.minecraft.net/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    
    mappings loom.layered() {
        officialMojangMappings()
    }

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    def version = project.version
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

// Java 25 derleme ayarı (Toolchain)
java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}
