- name: Set up JDK 21 (Gradle Runner için)
  uses: actions/setup-java@v4
  with:
    distribution: 'temurin'
    java-version: '21'

- name: Set up JDK 25 (Derleme için)
  uses: actions/setup-java@v4
  with:
    distribution: 'temurin'
    java-version: '25'

- name: Build with Gradle
  run: ./gradlew build --no-daemon
